# 1. Import Dependecies


In [1]:
%pip install gym[box2d] pyglet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 962.1/962.1 kB 426.3 kB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [2]:
import os
import gymnasium as gym
from stable_baselines3 import PPO
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.vec_env import DummyVecEnv
import numpy as np

# 2. Test Environment


In [3]:
env_name= 'CarRacing-v3'
env= gym.make(env_name, render_mode="human")

In [ ]:
env.reset()
env.action_space
env.observation_space

True

: 

In [4]:
episodes = 5
for episode in range(1, episodes + 1):
    obs = env.reset()  # Esto debería devolver una sola observación
    done = False
    score = 0

    while not done:
        env.render()

        action = env.action_space.sample()
        action = np.float32(action)

        obs, reward, done,truncated, info = env.step(action)
        score += reward
    print(f'Episode: {episode}, Score: {score}')

[0.49688488 0.49500665 0.92547554]
[-0.27284414  0.5117337   0.43516088]
[0.77246535 0.6763288  0.83965683]
[0.09121664 0.4019299  0.8963915 ]
[0.48763853 0.14129816 0.9058147 ]
[-0.75208753  0.6979244   0.2417712 ]
[-0.652465   0.4421041  0.3493738]
[-0.07953607  0.4812556   0.6595762 ]
[-0.11554396  0.8074524   0.7869379 ]
[-0.13346362  0.5857117   0.14557256]
[0.12682877 0.9110964  0.50980425]
[0.66232705 0.24945858 0.1409779 ]
[0.61616147 0.8315406  0.5868825 ]
[-0.96554893  0.6006056   0.38772285]
[0.50833446 0.976712   0.45809028]
[0.48343524 0.23162366 0.35194135]
[0.7664842 0.6488863 0.6114911]
[0.48938704 0.30861932 0.25357866]
[-0.42716095  0.7006175   0.74783176]
[0.42997235 0.89001703 0.9546029 ]
[0.43149638 0.67098016 0.30892545]
[0.8420857  0.49073684 0.5688232 ]
[-0.97404736  0.2698223   0.38411868]
[0.5026343  0.08542765 0.25318342]
[-0.24034064  0.94196284  0.88103724]
[0.2398233  0.64928097 0.33692896]
[-0.7489658   0.58365875  0.79683506]
[-0.9050836   0.18231364  0.

KeyboardInterrupt: 

In [5]:
env.close()

# 3. Vectorise Env and Train model


In [7]:
env= gym.make(env_name, render_mode="human")
env= DummyVecEnv([lambda: env])

In [ ]:
log_path= os.path.join('Training', 'Logs')
model= PPO('CnnPolicy', env, device='cuda', verbose=1, tensorboard_log=log_path)

Using cpu device
Wrapping the env in a VecTransposeImage.


: 

In [9]:
model.learn(total_timesteps=10000)

Logging to Training\Logs\PPO_1
-----------------------------
| time/              |      |
|    fps             | 47   |
|    iterations      | 1    |
|    time_elapsed    | 43   |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 43          |
|    iterations           | 2           |
|    time_elapsed         | 93          |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008404974 |
|    clip_fraction        | 0.0799      |
|    clip_range           | 0.2         |
|    entropy_loss         | -4.24       |
|    explained_variance   | -0.00295    |
|    learning_rate        | 0.0003      |
|    loss                 | 0.24        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.00682    |
|    std                  | 0.988       |
|    value_loss           | 0.627       |
---

KeyboardInterrupt: 

# 4. Save and Reload Mode


In [ ]:
PPO_path=os.path.join('Training', 'Saved Models', 'PPO_CarRacing')

In [ ]:
model.save(PPO_path)

In [ ]:
model= PPO.load(PPO_path, env=env)

# 5. Evaluate Test


In [ ]:
evaluate_policy(model,env, n_eval_episodes=10, render=True)

In [ ]:
env.close()